-- AlterTable
ALTER TABLE `profile` ADD COLUMN `city` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `displayName` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `dob` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `gender` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `location` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `primaryLanguage` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `spamCount` INTEGER NULL DEFAULT 0,
    ADD COLUMN `tz` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `zip` VARCHAR(191) NULL DEFAULT '';
