import { Inter } from "next/font/google";
import "../globals.css";
import Themed from "./themed";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Konexxu - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="xxdark">
      <body className={`${inter.className} blue-gray-50 dark:bg-blue-gray-800`}>
        <Themed children={children} ></Themed>



      </body>
    </html>
  );
}
